### ISSUE TITLE
Didn't receive any movies issue

### ISSUE THREAD

**Issue by alex21** [Diblo/KODI-Popcorn-Time#83]
I have this issue: Didn't receive any movies issue
Can't fetching content..

I'm using KODI-Popcorn-Time v0.7.0 alpha 2
Please help.

![screenshot 2015-11-12 12 17 30](https://cloud.githubusercontent.com/assets/13554635/11117156/afbcb72a-8937-11e5-85a0-151122ea2473.png)
![screenshot 2015-11-12 12 18 08](https://cloud.githubusercontent.com/assets/13554635/11117158/afe1b7aa-8937-11e5-94d3-536ce7fbd89a.png)

**Comment by Frepke** [comment]
Hello alex21,

YTS (the movie source) shuts down 4ever: https://torrentfreak.com/yify-yts-shuts-down-the-end-of-a-piracy-icon-151030/

**Comment by uzumakichiho** [comment]
But here they say that popcorn time is working again.
Maybe the this addon could work again too :D

https://www.reddit.com/r/PopCornTime/comments/3sbsz6/download_working_installers_or_fix_your_current/

https://torrentfreak.com/popcorn-times-alive-full-comeback-in-the-works-151117/

**Comment by Bnaya** [comment]
waiting for updates :)

**Comment by leandrotsampa** [comment]
Add this source in Settings:

https://yts.ag

And you will be happy ;D

**Comment by Bnaya** [comment]
Now i have this error
![screen shot 2015-12-01 at 2 45 01 pm](https://cloud.githubusercontent.com/assets/1304862/11501087/2a9bb9a8-983a-11e5-9e27-d0bc73cbb189.png)

**Comment by leandrotsampa** [comment]
Check kodi log and post here for analyze.

**Comment by Bnaya** [comment]
I think this is the relevant part
```
14:45:00 T:123145303453696   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'get'
                                            Traceback (most recent call last):
                                              File "/Users/bnaya/Library/Application Support/Kodi/addons/plugin.video.kodipopcorntime/addon.py", line 7, in <module>
                                                plugin.run()
                                              File "/Users/bnaya/Library/Application Support/Kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/xbmcswift2/plugin.py", line 334, in run
                                                items = self._dispatch(self.request.path)
                                              File "/Users/bnaya/Library/Application Support/Kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/xbmcswift2/plugin.py", line 306, in _dispatch
                                                listitems = view_func(**items)
                                              File "/Users/bnaya/Library/Application Support/Kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/caching.py", line 54, in _fn
                                                return result["value"]
                                              File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.6/contextlib.py", line 34, in __exit__
                                              File "/Users/bnaya/Library/Application Support/Kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/caching.py", line 36, in shelf
                                                yield d["data"]
                                              File "/Users/bnaya/Library/Application Support/Kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/caching.py", line 47, in _fn
                                                ret = fn(*a, **kwds)
                                              File "/Users/bnaya/Library/Application Support/Kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/utils.py", line 89, in _fn
                                                items = list(items)
                                              File "/Users/bnaya/Library/Application Support/Kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/library.py", line 121, in _fn
                                                for item in items:
                                              File "/Users/bnaya/Library/Application Support/Kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/scrapers/yify.py", line 104, in show_data
                                                movies = search_result.get("data").get("movies") or []
                                            AttributeError: 'NoneType' object has no attribute 'get'
                                            -->End of Python script error report<--
```

**Comment by alex21** [comment]
Works with 0.7.0 alpha2
Some category works, but with Recently added and Search I get error.
![error](https://cloud.githubusercontent.com/assets/13554635/11501909/dcd6adec-9837-11e5-8855-5232ee763e15.jpg)

**Comment by leandrotsampa** [comment]
Hmmm try again.
I make test now using version v0.7.0 alpha 2 and not have any problem.
I checked all options.

**Comment by leandrotsampa** [comment]
movies = search_result.get("data").get("movies") or []
 AttributeError: 'NoneType' object has no attribute 'get'

The error occurred why the search not found none movie .
Is missing a return treatment of there, but this not have nothing to do with a source of movies.

**Comment by alex21** [comment]
Works. You are right. The error occurred when the move not found .
Thanks.

**Comment by Bnaya** [comment]
I'm trying alpha 2, where in the settings i should put https://yts.ag/?

**Comment by alex21** [comment]
![server](https://cloud.githubusercontent.com/assets/13554635/11527699/d4d8b120-98e2-11e5-857e-47ea0c3cc7cf.jpg)

**Comment by Bnaya** [comment]
works, Thanks!
