### ISSUE TITLE
[Rasp PI2] fail to load second page of movies

### ISSUE THREAD

**Issue by Sixdsn** [Diblo/KODI-Popcorn-Time#74]
Hi,

I'm having an issue when clicking on "next page" in the movie list, it fails to load content.
I'm using the last osmc/kodi/popcorntime stable version.
Here are the logs:

20:21:55 742.488647 T:1606415392  NOTICE: -->Python Interpreter Initialized<--
20:21:56 743.852661 T:1606415392 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
20:21:57 743.948120 T:1606415392 WARNING: Previous line repeats 4 times.
20:21:57 743.948303 T:1606415392  NOTICE: [xbmcswift2] Request for "/browse/rating/all/2" matches rule for function "movies"
20:24:05 872.590332 T:1606415392  NOTICE: Traceback (most recent call last):
20:24:05 872.590576 T:1606415392  NOTICE:   File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/addon.py", line 7, in <module>
20:24:05 872.590698 T:1606415392  NOTICE:     plugin.run()
20:24:05 872.590820 T:1606415392  NOTICE:   File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/xbmcswift2/plugin.py", line 334, in run
20:24:05 872.590881 T:1606415392  NOTICE:     items = self._dispatch(self.request.path)
20:24:05 872.591003 T:1606415392  NOTICE:   File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/xbmcswift2/plugin.py", line 306, in _dispatch
20:24:05 872.591125 T:1606415392  NOTICE:     listitems = view_func(**items)
20:24:05 872.591187 T:1606415392  NOTICE:   File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/caching.py", line 47, in _fn
20:24:05 872.591309 T:1606415392  NOTICE:     ret = fn(*a, **kwds)
20:24:05 872.591431 T:1606415392  NOTICE:   File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/utils.py", line 89, in _fn
20:24:05 872.591492 T:1606415392  NOTICE:     items = list(items)
20:24:05 872.591614 T:1606415392  NOTICE:   File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/library.py", line 121, in _fn
20:24:05 872.591736 T:1606415392  NOTICE:     for item in items:
20:24:05 872.591858 T:1606415392  NOTICE:   File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/scrapers/yify.py", line 104, in show_data
20:24:05 872.591919 T:1606415392  NOTICE:     movies = search_r20:21:55 742.488647 T:1606415392  NOTICE: -->Python Interpreter Initialized<--
20:21:56 743.852661 T:1606415392 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
20:21:57 743.948120 T:1606415392 WARNING: Previous line repeats 4 times.
20:21:57 743.948303 T:1606415392  NOTICE: [xbmcswift2] Request for "/browse/rating/all/2" matches rule for function "movies"
20:24:05 872.590332 T:1606415392  NOTICE: Traceback (most recent call last):
20:24:05 872.590576 T:1606415392  NOTICE:   File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/addon.py", line 7, in <module>
20:24:05 872.590698 T:1606415392  NOTICE:     plugin.run()
20:24:05 872.590820 T:1606415392  NOTICE:   File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/xbmcswift2/plugin.py", line 334, in run
20:24:05 872.590881 T:1606415392  NOTICE:     items = self._dispatch(self.request.path)
20:24:05 872.591003 T:1606415392  NOTICE:   File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/xbmcswift2/plugin.py", line 306, in _dispatch
20:24:05 872.591125 T:1606415392  NOTICE:     listitems = view_func(**items)
20:24:05 872.591187 T:1606415392  NOTICE:   File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/caching.py", line 47, in _fn
20:24:05 872.591309 T:1606415392  NOTICE:     ret = fn(*a, **kwds)
20:24:05 872.591431 T:1606415392  NOTICE:   File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/utils.py", line 89, in _fn
20:24:05 872.591492 T:1606415392  NOTICE:     items = list(items)
20:24:05 872.591614 T:1606415392  NOTICE:   File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/library.py", line 121, in _fn
20:24:05 872.591736 T:1606415392  NOTICE:     for item in items:
20:24:05 872.591858 T:1606415392  NOTICE:   File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/scrapers/yify.py", line 104, in show_data
20:24:05 872.591919 T:1606415392  NOTICE:     movies = search_result.get("data").get("movies") or []
20:24:05 872.592041 T:1606415392  NOTICE: AttributeError: 'NoneType' object has no attribute 'get'
20:24:05 872.593567 T:1606415392   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'get'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/addon.py", line 7, in <module>
                                                plugin.run()
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/xbmcswift2/plugin.py", line 334, in run
                                                items = self._dispatch(self.request.path)
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/xbmcswift2/plugin.py", line 306, in _dispatch
                                                listitems = view_func(**items)
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/caching.py", line 47, in _fn
                                                ret = fn(*a, **kwds)
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/utils.py", line 89, in _fn
                                                items = list(items)
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/library.py", line 121, in _fn
                                                for item in items:
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/scrapers/yify.py", line 104, in show_data
                                                movies = search_result.get("data").get("movies") or []
                                            AttributeError: 'NoneType' object has no attribute 'get'
                                            -->End of Python script error report<--
20:24:05 872.741089 T:1958269488   ERROR: GetDirectory - Error getting plugin://plugin.video.kodipopcorntime/browse/rating/all/2?limit=20&order=desc
20:24:05 872.744263 T:1958269488   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.kodipopcorntime/browse/rating/all/2?limit=20&order=desc) failed
20:24:05 872.786255 T:1606415392  NOTICE: Thread BackgroundLoader start, auto delete: false
20:25:06 933.688538 T:1606415392  NOTICE: Previous line repeats 1 times.
20:25:06 933.689026 T:1606415392  NOTICE: Thread JobWorker start, auto delete: true
20:25:13 940.127258 T:1614804000  NOTICE: Thread LanguageInvoker start, auto delete: false
20:25:13 940.494019 T:1614804000  NOTICE: -->Python Interpreter Initialized<--
20:25:14 941.794922 T:1614804000 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
20:25:15 941.894592 T:1614804000 WARNING: Previous line repeats 4 times.esult.get("data").get("movies") or []
20:24:05 872.592041 T:1606415392  NOTICE: AttributeError: 'NoneType' object has no attribute 'get'
20:24:05 872.593567 T:1606415392   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'get'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/addon.py", line 7, in <module>
                                                plugin.run()
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/xbmcswift2/plugin.py", line 334, in run
                                                items = self._dispatch(self.request.path)
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/xbmcswift2/plugin.py", line 306, in _dispatch
                                                listitems = view_func(**items)
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/caching.py", line 47, in _fn
                                                ret = fn(*a, **kwds)
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/utils.py", line 89, in _fn
                                                items = list(items)
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/library.py", line 121, in _fn
                                                for item in items:
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/scrapers/yify.py", line 104, in show_data
                                                movies = search_result.get("data").get("movies") or []
                                            AttributeError: 'NoneType' object has no attribute 'get'
                                            -->End of Python script error report<--
20:24:05 872.741089 T:1958269488   ERROR: GetDirectory - Error getting plugin://plugin.video.kodipopcorntime/browse/rating/all/2?limit=20&order=desc
20:24:05 872.744263 T:1958269488   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.kodipopcorntime/browse/rating/all/2?limit=20&order=desc) failed
20:24:05 872.786255 T:1606415392  NOTICE: Thread BackgroundLoader start, auto delete: false
20:25:06 933.688538 T:1606415392  NOTICE: Previous line repeats 1 times.
20:25:06 933.689026 T:1606415392  NOTICE: Thread JobWorker start, auto delete: true
20:25:13 940.127258 T:1614804000  NOTICE: Thread LanguageInvoker start, auto delete: false
20:25:13 940.494019 T:1614804000  NOTICE: -->Python Interpreter Initialized<--
20:25:14 941.794922 T:1614804000 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
20:25:15 941.894592 T:1614804000 WARNING: Previous line repeats 4 times.

**Comment by Diblo** [comment]
Hi @Sixdsn 
Try this Alpha version to see if it works. https://github.com/Diblo/KODI-Popcorn-Time/wiki/Download#test-alpha-version-066

**Comment by Sixdsn** [comment]
Hi,

Thanks for the quick answer, it's working with 0.7.0alpha2

**Comment by Diblo** [comment]
:+1:
